name: Baixando Lista

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositório
      uses: actions/checkout@v4

    - name: Configurar Ambiente Virtual
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Instalar Dependências Python
      run: |
        source venv/bin/activate
        pip install streamlink selenium requests beautifulsoup4 lxml python-dateutil yt-dlp youtube-dl pytz

    - name: Instalar ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg      

    - name: Executar script Python
      run: |
        source venv/bin/activate
        python agrupadordelistas.py

    - name: Commit e Push das Alterações
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git pull --rebase origin main
        git add -A
        git commit -m "Atualizar lista baixada" || echo "Nada para commitar"
        git push origin main
