name: Baixando Lista

on:
  schedule:
    - cron: '0 */2 * * *'  # Executar a cada 2 horas
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositório
      uses: actions/checkout@v4

    - name: Configurar Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Deletar Log
      run: |
        rm -rf ./log.txt

    - name: Instalando dependências
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install streamlink selenium requests beautifulsoup4 lxml python-dateutil yt-dlp youtube-dl pytz gdown

    - name: Verificar versão do Python
      run: |
        python3 --version

    - name: Rodar script pt.py
      run: |
        python3 pt.py

    - name: Adicionar Mudanças ao Controle de Versão
      run: |
        git add -A
        git status

    - name: Garantir alterações mais recentes do repositório remoto
      run: |
        git pull origin main || echo "Erro ao fazer pull, pode ser que já tenha as últimas alterações."

    - name: Commit e Push
      run: |
        git commit -m "Atualizar lista baixada" || echo "Nenhuma mudança para commitar."
        git push origin main || echo "Erro ao fazer push. Pode ser necessário revisar conflitos."
